---
Name: 'TemplateoverviewRoutes'
After: framework
---
SilverStripe\Control\Director:
  rules:
    'templates//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\TemplateOverviewPageController'
