---
Name: 'TemplateoverviewRoutes'
Before:
  - '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'admin/templates//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\TemplateOverviewPageController'
    'admin/templates-elemental//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\TemplateOverviewForElementalPageController'
    'admin/templateoverviewloginandredirect//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\LoginAndRedirect'
    'admin/templateoverviewsmoketestresponse//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\CheckAllTemplatesResponseController'
