---
Name: 'TemplateoverviewRoutes'
---
SilverStripe\Control\Director:
  rules:
    'templates//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\TemplateOverviewPageController'
    'templatesloginandredirect//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\LoginAndRedirect'
