---
Name: 'TemplateoverviewRoutes'
---
SilverStripe\Control\Director:
  rules:
    'templateoverviewtemplates//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\TemplateOverviewPageController'
    'templateoverviewtemplates-elemental//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\TemplateOverviewForElementalPageController'
    'templateoverviewloginandredirect//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\LoginAndRedirect'
    'templateoverviewsmoketestresponse//$Action/$ID/$OtherID/$Version': 'Sunnysideup\TemplateOverview\Control\CheckAllTemplatesResponseController'
